In [58]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
!pip install names
import names

Requirement already satisfied: names in /usr/local/lib/python3.10/dist-packages (0.3.0)

In [60]:
# Generate 500 unique author names with IDs
author_ids = [str(i).zfill(3) for i in range(1, 501)]  # IDs formatted as
                                                       # 001, 002, ..., 500

author_names = set()

while len(author_names) < 500:
    # Generate random full name using names library
    author_name = names.get_full_name()
    # Add unique author names to the set to prevent duplicates
    author_names.add(author_name)

# Convert set back to a list for consistency
author_names = list(author_names)

# Generate birth dates in the format dd,mm,yyyy
def generate_birthdate():
    start_date = datetime(1950, 1, 1)  # Start date for birth year
    end_date = datetime(2000, 12, 31)   # End date for birth year
    random_date = start_date + \
                timedelta(days=random.randint(0, (end_date - start_date).days))
    return random_date.strftime('%Y-%m-%d')

birth_dates = [generate_birthdate() for _ in range(500)]

# Generate 50 random original countries
# List of 50 random countries
countries = ["USA", "Canada", "UK", "Australia", "Germany", "France", "Japan",
             "China", "India", "Brazil", "Mexico", "Italy", "Spain",
             "Netherlands", "South Korea", "Russia", "Argentina", "Sweden",
             "Norway", "Denmark", "Finland", "Portugal", "Greece", "Turkey",
             "Egypt", "South Africa", "Kenya", "Nigeria", "New Zealand",
             "Singapore", "Malaysia", "Thailand", "Vietnam", "Indonesia",
             "Philippines", "Pakistan", "Bangladesh", "Sri Lanka", "Iran",
             "Iraq", "Saudi Arabia", "United Arab Emirates", "Qatar", "Kuwait",
             "Oman", "Bahrain", "Jordan", "Lebanon", "Israel"]
author_countries = random.choices(countries, k=500)

# Create Authors DataFrame
authors_df = pd.DataFrame({
    'AuthorID': author_ids,
    'AuthorName': author_names,
    'BirthDate': birth_dates,
    'Country': author_countries
})

# Set AuthorID as the primary key for Authors table
authors_df.set_index('AuthorID', inplace=True)

# Print the first few rows of Authors DataFrame
print(authors_df)

                  AuthorName   BirthDate      Country
AuthorID
001       Catherine Benshoof  1992-05-29      Lebanon
002         Eugene Hernandez  1981-11-10       Mexico
003           Allan Williams  1974-03-29    Argentina
004          Christine Smith  1973-09-28  Philippines
005            Bertha Garcia  1972-10-19       Mexico
...                      ...         ...          ...
496             Cherie Meyer  1966-04-06     Portugal
497          Lucretia Batten  1970-02-15          USA
498         Caroline England  1954-09-14        China
499         Stanton Chilcutt  1960-03-23     Pakistan
500       Teresia Caporiccio  1984-02-15       France

[500 rows x 3 columns]

In [61]:
authors_df

                  AuthorName   BirthDate      Country
AuthorID
001       Catherine Benshoof  1992-05-29      Lebanon
002         Eugene Hernandez  1981-11-10       Mexico
003           Allan Williams  1974-03-29    Argentina
004          Christine Smith  1973-09-28  Philippines
005            Bertha Garcia  1972-10-19       Mexico
...                      ...         ...          ...
496             Cherie Meyer  1966-04-06     Portugal
497          Lucretia Batten  1970-02-15          USA
498         Caroline England  1954-09-14        China
499         Stanton Chilcutt  1960-03-23     Pakistan
500       Teresia Caporiccio  1984-02-15       France

[500 rows x 3 columns]

In [62]:
# List of 30 realistic unique genre names
genre_names_list = ["Mystery", "Romance", "Thriller", "Science Fiction",
                    "Fantasy", "Historical Fiction", "Horror", "Drama",
                    "Adventure", "Crime", "Biography", "Self-Help", "Cooking",
                    "Travel", "Science", "Poetry", "Humor", "Young Adult",
                    "Children", "Graphic Novel", "Memoir", "Satire",
                    "Paranormal", "Psychology", "Philosophy", "Religion",
                    "Classic", "Contemporary", "Western", "Non-Fiction"]

# Generate 300 unique combinations of genres
genre_combinations = set()
while len(genre_combinations) < 300:
    combination = ', '.join(random.sample(genre_names_list,
                                          k=random.randint(1, 5)))
    genre_combinations.add(combination)

# Create GenreID for each unique genre combination
genre_ids = [str(i).zfill(3) for i in range(1, 301)]  # IDs formatted as
                                                      # 001, 002, ..., 300

# Create Genres DataFrame
genres_df = pd.DataFrame({
    'GenreID': genre_ids,
    'GenreName': list(genre_combinations)
})

# Set GenreID as the primary key for Genres table
genres_df.set_index('GenreID', inplace=True)

# Print the first few rows of Genres DataFrame
print(genres_df)

                                                 GenreName
GenreID
001               Romance, Fantasy, Philosophy, Psychology
002      Self-Help, Paranormal, Young Adult, Thriller, ...
003                                            Non-Fiction
004                                       Satire, Children
005                                        Fantasy, Satire
...                                                    ...
296                                        Humor, Religion
297                       Romance, Science, Humor, Mystery
298      Western, Non-Fiction, Paranormal, Children, My...
299                        Religion, Poetry, Graphic Novel
300                                         Drama, Fantasy

[300 rows x 1 columns]

In [63]:
genres_df

                                                 GenreName
GenreID
001               Romance, Fantasy, Philosophy, Psychology
002      Self-Help, Paranormal, Young Adult, Thriller, ...
003                                            Non-Fiction
004                                       Satire, Children
005                                        Fantasy, Satire
...                                                    ...
296                                        Humor, Religion
297                       Romance, Science, Humor, Mystery
298      Western, Non-Fiction, Paranormal, Children, My...
299                        Religion, Poetry, Graphic Novel
300                                         Drama, Fantasy

[300 rows x 1 columns]

In [64]:
# Generate 100 unique publisher names
publisher_names = set()
while len(publisher_names) < 100:
    name = names.get_full_name() + " Publishers"
    publisher_names.add(name)

# Generate PublisherID for each unique publisher name
publisher_ids = [str(i).zfill(3) for i in range(1, 101)]  # IDs formatted
                                                          # as 001, 002,..., 100

# Create Publishers DataFrame
publishers_df = pd.DataFrame({
    'PublisherID': publisher_ids,
    'PublisherName': list(publisher_names)
})

# Set PublisherID as the primary key for Publishers table
publishers_df.set_index('PublisherID', inplace=True)

# Print the first few rows of Publishers DataFrame
print(publishers_df)

                             PublisherName
PublisherID
001           Jessica Bannister Publishers
002            Jessica Anderson Publishers
003             James Wakefield Publishers
004               Camille Beebe Publishers
005                   Don Dolfi Publishers
...                                    ...
096           Michael Turnquist Publishers
097          Gwendolyn Martinez Publishers
098              Shannon Blanco Publishers
099               Ernest Kerwin Publishers
100           Herman Wedgeworth Publishers

[100 rows x 1 columns]

In [65]:
publishers_df

                             PublisherName
PublisherID
001           Jessica Bannister Publishers
002            Jessica Anderson Publishers
003             James Wakefield Publishers
004               Camille Beebe Publishers
005                   Don Dolfi Publishers
...                                    ...
096           Michael Turnquist Publishers
097          Gwendolyn Martinez Publishers
098              Shannon Blanco Publishers
099               Ernest Kerwin Publishers
100           Herman Wedgeworth Publishers

[100 rows x 1 columns]

In [66]:
# Generate 1500 unique borrower names
borrower_names = set()
while len(borrower_names) < 1500:
    # Generate random full name using names library
    full_name = names.get_full_name()
    # Add unique borrower names to the set to prevent duplicates
    borrower_names.add(full_name)

# Convert set back to a list for consistency
borrower_names = list(borrower_names)

# Generate BorrowerID for each unique borrower name
borrower_ids = [str(i).zfill(4) for i in range(1, 1501)]  # IDs formatted
                                                          # as 0001, 0002, ..., 1500

# Generate MembershipType for borrowers
membership_types = ["Monthly", "Semi-Annually", "Annually",
                    "Lifetime", "Weekly"]
borrower_membership_types = random.choices(membership_types, k=1500)

# Generate random overdue fees centered around 0
overdue_fees = np.random.normal(loc=0, scale=20, size=1500)  # Using a standard deviation of 20 for illustration
overdue_fees = abs(overdue_fees).round(2)

# Create Borrowers DataFrame
borrowers_df = pd.DataFrame({
    'BorrowerID': borrower_ids,
    'BorrowerName': borrower_names,
    'MembershipType': borrower_membership_types,
    'OverdueFeesAmount': overdue_fees
})

# Choose 5 random rows from borrowers_df
random_rows = borrowers_df.sample(n=5, random_state=42)

# Create duplicates of the selected random rows
duplicate_rows = pd.concat([random_rows] * 3, ignore_index=True)

# Select 15 random indices to insert values
indices_to_replace = random.sample(borrowers_df.index.tolist(), 15)

# Select columns to replace with duplicates
columns_to_replace = ['BorrowerName', 'MembershipType', 'OverdueFeesAmount']

# Replace selected columns with duplicates in the original DataFrame
for column in columns_to_replace:
    borrowers_df.loc[indices_to_replace, column] = duplicate_rows[column]

# Set BorrowerID as the primary key for Borrowers table
borrowers_df.set_index('BorrowerID', inplace=True)

# Print the first few rows of Borrowers DataFrame
print(borrowers_df)

                BorrowerName MembershipType  OverdueFeesAmount
BorrowerID
0001           Karen Settles       Annually               3.66
0002        Stephanie Weaver       Annually              43.24
0003             Norris Kent       Annually              25.91
0004            Alisa Adkins       Annually               2.29
0005             Betty Doman         Weekly              13.55
...                      ...            ...                ...
1496            Martha Evans        Monthly              42.29
1497           Sandra Chacon       Annually              48.18
1498           Robert Osgood       Annually               7.41
1499         Patrick Mcneill  Semi-Annually               4.56
1500             Lydia Brown       Annually               6.14

[1500 rows x 3 columns]

In [67]:
# Check for duplicate index values in borrowers_df
duplicate_indices = borrowers_df.index.duplicated()
print("Duplicate indices in borrowers_df:", duplicate_indices.any())

Duplicate indices in borrowers_df: False

In [68]:
borrowers_df

                BorrowerName MembershipType  OverdueFeesAmount
BorrowerID
0001           Karen Settles       Annually               3.66
0002        Stephanie Weaver       Annually              43.24
0003             Norris Kent       Annually              25.91
0004            Alisa Adkins       Annually               2.29
0005             Betty Doman         Weekly              13.55
...                      ...            ...                ...
1496            Martha Evans        Monthly              42.29
1497           Sandra Chacon       Annually              48.18
1498           Robert Osgood       Annually               7.41
1499         Patrick Mcneill  Semi-Annually               4.56
1500             Lydia Brown       Annually               6.14

[1500 rows x 3 columns]

In [69]:
# Generate unique BorrowingID for 3000 values
borrowing_ids = [str(i).zfill(5) for i in range(1, 3001)]  # IDs formatted as 00001, 00002, ..., 03000

# Generate BookID and BorrowerID for 1100 books and 1500 borrowers respectively
book_ids = [str(i).zfill(4) for i in range(1, 1101)]  # IDs formatted as 0001, 0002, ..., 1100
borrower_ids = [str(i).zfill(4) for i in range(1, 1501)]  # IDs formatted as 0001, 0002, ..., 1500

# Generate BorrowDate and ReturnDate for each BorrowingID
borrow_dates = []
return_dates = []

for _ in range(3000):
    # Randomly select a BookID and BorrowerID
    book_id = random.choice(book_ids)
    borrower_id = random.choice(borrower_ids)

    # Generate a random BorrowDate
    borrow_date = datetime(random.randint(2002, 2022),
                           random.randint(1, 12), random.randint(1, 28))

    # Calculate a random number of days between 1 and 30 for the borrowing period
    borrowing_period = random.randint(1, 30)

    # Calculate ReturnDate based on BorrowDate and random borrowing period
    return_date = borrow_date + timedelta(days=borrowing_period)

    # Ensure no two borrowers can borrow the same book in the same timeframe
    # and that no book falls within the range of another borrowing event
    while any(
        (book_id == existing_book_id and borrow_date <= existing_return_date \
         <= return_date) or
        (borrow_date <= existing_borrow_date <= return_date and book_id == \
         existing_book_id)
        for existing_book_id, existing_borrow_date, existing_return_date in zip(
            book_ids,
            borrow_dates,
            return_dates
        )
    ):
        book_id = random.choice(book_ids)
        borrow_date = datetime(random.randint(2002, 2022),
                               random.randint(1, 12), random.randint(1, 28))
        borrowing_period = random.randint(1, 30)
        return_date = borrow_date + timedelta(days=borrowing_period)


    borrow_dates.append(borrow_date)
    return_dates.append(return_date)

# Create Borrowing History DataFrame
borrowing_history_df = pd.DataFrame({
    'BorrowingID': borrowing_ids,
    'BookID': random.choices(book_ids, k=3000),
    'BorrowerID': random.choices(borrower_ids, k=3000),
    'BorrowDate': borrow_dates,
    'ReturnDate': return_dates
})

# Randomly select 50 indices to set as missing values in the 'ReturnDate' column
missing_indices = random.sample(range(len(borrowing_history_df)), 50)

# Set the selected indices in the 'ReturnDate' column as NaN (missing values)
borrowing_history_df.loc[missing_indices, 'ReturnDate'] = np.nan

# Set the compound key as the index for Borrowing History table
borrowing_history_df.set_index(['BookID', 'BorrowingID'], inplace=True)

# Sort the DataFrame by BookID and BorrowingID (Compound Key)
borrowing_history_df.sort_index(inplace=True)

# Print the first few rows of Borrowing History DataFrame
print(borrowing_history_df)

                   BorrowerID BorrowDate ReturnDate
BookID BorrowingID
0001   01105             0371 2022-06-14 2022-07-08
       02290             0179 2020-09-17 2020-10-15
0002   00693             1450 2012-03-19 2012-03-24
       01235             0592 2010-10-13 2010-11-10
       01527             0153 2007-09-22 2007-09-26
...                       ...        ...        ...
1099   00210             0882 2004-11-05 2004-11-30
       02025             0085 2007-01-27 2007-02-18
       02144             1127 2017-05-14 2017-05-18
1100   02339             1078 2007-07-14 2007-08-03
       02495             0899 2004-08-10 2004-08-17

[3000 rows x 3 columns]

In [70]:
borrowing_history_df

                   BorrowerID BorrowDate ReturnDate
BookID BorrowingID
0001   01105             0371 2022-06-14 2022-07-08
       02290             0179 2020-09-17 2020-10-15
0002   00693             1450 2012-03-19 2012-03-24
       01235             0592 2010-10-13 2010-11-10
       01527             0153 2007-09-22 2007-09-26
...                       ...        ...        ...
1099   00210             0882 2004-11-05 2004-11-30
       02025             0085 2007-01-27 2007-02-18
       02144             1127 2017-05-14 2017-05-18
1100   02339             1078 2007-07-14 2007-08-03
       02495             0899 2004-08-10 2004-08-17

[3000 rows x 3 columns]

In [71]:
# Count the missing values in each column
missing_values_sum = borrowing_history_df.isnull().sum()

# Print the sum of missing values for each column
print(missing_values_sum)

BorrowerID     0
BorrowDate     0
ReturnDate    50
dtype: int64

In [72]:
# Expanded lists for versatile titles
topics = ['Sports', 'Messi', 'Football', 'Soccer', 'Basketball', 'Tennis', \
          'Golf', 'Hockey', 'Baseball', 'Cycling', 'Athletics', 'Swimming', \
          'Cricket', 'Rugby', 'Volleyball', 'Boxing', 'Wrestling', 'Skating', \
          'Chess', 'Poker', 'Fishing', 'Hiking', 'Camping', 'Cooking', \
          'Travel', 'History', 'Science', 'Fiction', 'Mystery', 'Romance', \
          'Adventure', 'Fantasy']
words = ['Incredible', 'Unbelievable', 'Spectacular', 'Mind-Blowing', \
         'Staggering', 'Incredulous', 'Astonishing', 'Breathtaking', \
         'Fascinating', 'Remarkable', 'Extraordinary', 'Astounding', \
         'Amazing', 'Stunning', 'Striking', 'Impressive', 'Outstanding', \
         'Marvelous', 'Magnificent', 'Wonderful', 'Fantastic', 'Superb', \
         'Splendid', 'Gorgeous', 'Mesmerizing', 'Enchanting', 'Captivating', \
         'Inspirational', 'Creative', 'Thrilling', 'Compelling']
adjectives = ['Epic', 'Legendary', 'Heroic', 'Mythical', 'Glorious', 'Grand', \
              'Majestic', 'Noble', 'Regal', 'Sovereign', 'Proud', 'Triumphant',\
              'Victorious', 'Courageous', 'Valiant', 'Fearless', 'Brave', \
              'Bold', 'Daring', 'Fierce', 'Intrepid', 'Dauntless', \
              'Indomitable', 'Resolute', 'Tenacious', 'Stalwart', 'Sturdy', \
              'Robust', 'Mighty', 'Powerful']
verbs = ['Journey', 'Adventure', 'Quest', 'Expedition', 'Pilgrimage', \
         'Exploration', 'Odyssey', 'Discovery', 'Voyage', 'Excursion', \
         'Travels', 'Experiences', 'Encounters', 'Ventures', 'Escapade', \
         'Enterprise', 'Mission', 'Pursuit', 'Passage', 'Traversal', \
         'Traveling', 'Roaming', 'Wandering', 'Roar', 'Whisper', 'Echo', \
         'Ripple', 'Cascade', 'Twirl', 'Spiral', 'Sway', 'Glide']

# Function to generate versatile titles
def generate_title(topics_list, words_list, adjectives_list, verbs_list):
    topic = random.choice(topics_list)
    word = random.choice(words_list)
    adjective = random.choice(adjectives_list)
    verb = random.choice(verbs_list)
    title = '{} {} {}: A {} of {}'.format(adjective, word, topic, verb, topic)
    return title

# Generate 1100 unique titles
unique_titles = set()
while len(unique_titles) < 1100:
    title = generate_title(topics, words, adjectives, verbs)
    unique_titles.add(title)

# Convert set back to a list for consistency
unique_titles_list = list(unique_titles)

# Verify the number of unique titles generated
print(len(unique_titles_list))

# Print the first few unique titles
print(unique_titles_list[:10])  # Print the first 10 unique titles

1100
['Powerful Enchanting Chess: A Ventures of Chess', 'Legendary Incredulous Travel: A Escapade of Travel', 'Mighty Gorgeous Fiction: A Expedition of Fiction', 'Sovereign Inspirational Golf: A Ventures of Golf', 'Dauntless Gorgeous History: A Ripple of History', 'Daring Incredible Tennis: A Escapade of Tennis', 'Daring Astonishing Golf: A Mission of Golf', 'Brave Mesmerizing Cricket: A Ripple of Cricket', 'Dauntless Striking Athletics: A Ripple of Athletics', 'Glorious Fascinating Boxing: A Spiral of Boxing']

In [73]:
# Generate BookID for 1100 books
book_ids = [str(i).zfill(4) for i in range(1, 1101)]  # IDs formatted as 0001, 0002, ..., 1100

# Generate Title, AuthorID, GenreID, ISBN, PublishedYear, and PublisherID for each book
titles = unique_titles_list  # Sample titles

# Generate AuthorID, GenreID, and PublisherID
author_ids = random.choices([str(i).zfill(3) for i in range(1, 501)], k=1100)
genre_ids = random.choices([str(i).zfill(3) for i in range(1, 301)], k=1100)
publisher_ids = random.choices([str(i).zfill(2) for i in range(1, 101)], k=1100)

# Generate unique ISBNs (Unique Identifier, Nominal Data)
unique_isbns = set()
while len(unique_isbns) < 1100:
    isbn = random.randint(1000000000, 9999999999)  # 10-digit ISBN
    unique_isbns.add(isbn)

# Convert set back to a list for consistency
isbns = list(unique_isbns)

# Generate PublishedYear (Ordinal Data) for each book
published_years = []

for author_id in author_ids:
    # Find the corresponding birth year of the author
    author_birth_year = int(authors_df[authors_df.index == author_id]\
                             ['BirthDate'].values[0].split('-')[0])

    # Generate a random PublishedYear that is 25 years after the author's birth year
    published_year = random.randint(author_birth_year + 20, 2021)
    published_years.append(published_year)

# Generate random purchase prices for each book
purchase_prices = np.random.uniform(10, 70, 1100).round(2)  # Prices between $10 and $100

# Create Books DataFrame
books_df = pd.DataFrame({
    'BookID': book_ids,
    'Title': titles,
    'AuthorID': author_ids,
    'GenreID': genre_ids,
    'ISBN': isbns,
    'PublishedYear': published_years,
    'PublisherID': publisher_ids,
    'PurchasedPrice': purchase_prices
})

# Introduce 10 random missing values in 'PublishedYear' column
missing_published_year_indices = random.sample(range(len(books_df)), 10)
books_df.loc[missing_published_year_indices, 'PublishedYear'] = np.nan

books_df['PublishedYear'] = pd.to_datetime(books_df['PublishedYear'],
                                           format='%Y').dt.year

# Introduce 10 random missing values in 'PurchasePrice' column
missing_purchase_price_indices = random.sample(range(len(books_df)), 10)
books_df.loc[missing_purchase_price_indices, 'PurchasedPrice'] = np.nan

# Set BookID as the primary key for Books table
books_df.set_index('BookID', inplace=True)

# Print the first few rows of Books DataFrame
print(books_df)

                                                    Title AuthorID GenreID  \
BookID
0001       Powerful Enchanting Chess: A Ventures of Chess      095     268
0002    Legendary Incredulous Travel: A Escapade of Tr...      468     156
0003     Mighty Gorgeous Fiction: A Expedition of Fiction      021     249
0004     Sovereign Inspirational Golf: A Ventures of Golf      478     243
0005      Dauntless Gorgeous History: A Ripple of History      494     163
...                                                   ...      ...     ...
1096      Triumphant Gorgeous Tennis: A Mission of Tennis      452     009
1097     Fierce Magnificent Science: A Roaming of Science      253     261
1098    Sovereign Astounding Boxing: A Escapade of Boxing      283     028
1099        Bold Astounding Science: A Travels of Science      216     126
1100        Grand Creative Boxing: A Enterprise of Boxing      012     195

              ISBN  PublishedYear PublisherID  PurchasedPrice
BookID
0001    8220860420         2002.0          12           51.67
0002    8701452293         1997.0          01           28.93
0003    2642323461         2021.0          46           67.72
0004    3753222151         2020.0          20           51.17
0005    4190212100         1992.0          03           62.63
...            ...            ...         ...             ...
1096    4466438134         1992.0          21           54.33
1097    9580662778         2003.0          42           69.02
1098    2561492988         2012.0          27           28.76
1099    3091800061         2011.0          25           20.84
1100    5428531198         2020.0          99           51.34

[1100 rows x 7 columns]

In [74]:
books_df

,Title,AuthorID,GenreID,ISBN,PublishedYear,PublisherID,PurchasedPrice
BookID,,,,,,,
0001,Powerful Enchanting Chess: A Ventures of Chess,095,268,8220860420,2002.0,12,51.67
0002,Legendary Incredulous Travel: A Escapade of Tr...,468,156,8701452293,1997.0,01,28.93
0003,Mighty Gorgeous Fiction: A Expedition of Fiction,021,249,2642323461,2021.0,46,67.72
0004,Sovereign Inspirational Golf: A Ventures of Golf,478,243,3753222151,2020.0,20,51.17
0005,Dauntless Gorgeous History: A Ripple of History,494,163,4190212100,1992.0,03,62.63
...,...,...,...,...,...,...,...
1096,Triumphant Gorgeous Tennis: A Mission of Tennis,452,009,4466438134,1992.0,21,54.33
1097,Fierce Magnificent Science: A Roaming of Science,253,261,9580662778,2003.0,42,69.02
1098,Sovereign Astounding Boxing: A Escapade of Boxing,283,028,2561492988,2012.0,27,28.76
1099,Bold Astounding Science: A Travels of Science,216,126,3091800061,2011.0,25,20.84
1100,Grand Creative Boxing: A Enterprise of Boxing,012,195,5428531198,2020.0,99,51.34

In [75]:
# Count the missing values in each column
missing_values_sum = books_df.isnull().sum()

# Print the sum of missing values for each column
print(missing_values_sum)

Title              0
AuthorID           0
GenreID            0
ISBN               0
PublishedYear     10
PublisherID        0
PurchasedPrice    10
dtype: int64

In [76]:
# Save DataFrames to CSV files
authors_df.to_csv('authors.csv')
genres_df.to_csv('genres.csv')
publishers_df.to_csv('publishers.csv')
borrowers_df.to_csv('borrowers.csv')
books_df.to_csv('books.csv')
borrowing_history_df.to_csv('borrowing_history.csv')